name: Deploy React App
on:
  push:
    branches:
      - "master"
jobs:
  test_my_comp:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: windows-latest
    needs: test_my_comp
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Lint application
        run: npm run lint
  build:
    runs-on: windows-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy
        run: echo Deploying...
