name: Test React App
on: push
jobs:
  test_my_comp:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
